name: cpu-double-weak
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - pip
  - pip:
      - tensorflow-cpu
      - keras
      - nltk
      - spacy
      - transformers
      - black
      - mypy
      - nltk
      - spacy
      - transformers
      - accelerate
      - evaluate
      - jiwer
      - sentencepiece
      - hydra-core
      - strenum
      - wandb
      - librosa==0.10.*
      - soundfile==0.12.*