name: double-weak-cpu
channels:
  - defaults
dependencies:
  - python=3.10.*
  - numpy<2
  - pip
  - pip:
      - black
      - mypy
      - torch==2.*  
      - torchaudio==2.*
      - transformers==4.*
      - accelerate==1.0.*
      - evaluate==0.4.*
      - jiwer==3.*
      - sentencepiece==0.*
      - hydra-core==1.3.*
      - strenum
      - wandb==0.*
      - librosa==0.10.*
      - soundfile==0.12.*