name: cpu-pytorch-double-weak
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*
  - pip=23.*
  - black
  - mypy
  - numpy=1.21.*
  - pytorch=2.*
  - transformers=4.*
  - accelerate=1.0.*
  - evaluate=0.*
  # - sentencepiece=0.* # can omit if sentencepiece models (e.g. ALBERT, XLMRoberta, T5) are not needed
  - hydra-core=1.3.*
  - strenum
  # Loggers below; comment out/delete any that are not needed
  - neptune=1.*
  - tensorboard=2.*
  - wandb=0.*
  - pip:
    - librosa==0.10.*
    - soundfile==0.12.*