name: double-weak-cuda
channels:
  - defaults
dependencies:
  - python=3.10.*
  - pip
  - pip:
      - black
      - mypy
      - torch==2.*  # PyTorch
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - transformers==4.*
      - accelerate==1.0.*
      - evaluate==0.4.*
      - jiwer==3.*
      - sentencepiece==0.*  # Omit if not working with models requiring SentencePiece
      - hydra-core==1.3.*
      - strenum
      - wandb==0.*
      - librosa==0.10.*
      - soundfile==0.12.*