# config/evaluate.yaml
defaults:
  - data: huggingface
  - dataset: load_dataset
  - pipeline: automatic-speech-recognition
  - processor: from_pretrained
  - model: from_pretrained
  - metric: wer
  - stats: scipy/kruskal
  - _self_

model_id: openai/whisper-tiny.en #distil-whisper/distil-large-v3

batch_size: 32
sampling_rate: 16000

dataset:
  path: edinburghcstr/edacc  # Specify the dataset you want to use
  split: "validation[:10%]+validation[-10%:]"

processor:
  pretrained_model_name_or_path: ${model_id}

model:
  pretrained_model_name_or_path: ${model_id}

pipeline:
  model: ${model_id}

transcriptions_fname: transcriptions
results_fname: results
actual_transcription_field_name: text
predicted_transcription_field_name: transcriptions
bias_field_name: gender

hydra:
  job:
    name: distil-whisper
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

